language: node_js
node_js:
  - "5.0"
  - "4.0"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "npm run test-ci"
